version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/template"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    allow:
      - dependency-type: "direct"
    schedule:
      interval: "weekly"
    groups:
      egui:
        patterns:
          - "eframe"
          - "egui_extras"
      cargo-patch:
        update-types:
          - "patch"
