name: Markdownlint

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

permissions: {}

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: npx markdownlint-cli .

  markdownlint-complete:
    name: Markdownlint Complete
    if: ${{ always() }}
    needs: [markdownlint]
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs passed
        run: |
          if ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}; then
            echo "One or more jobs failed or were cancelled"
            exit 1
          fi
          echo "All jobs succeeded"
